export type CareType =
  | 'isAmbulantGeleverd'
  | 'isKlinischGeleverd'
  | 'isBejegening'
  | 'isVerzorging'
  | 'isVerpleging'
  | 'isBehandeling'
  | 'isBegeleiding'
  | 'isBescherming'
  | 'isVochtVoedingMedicatie'
  // | 'isMedischeControles'
  | 'isBeperkenBewegingsvrijheid'
  | 'isInsluiten'
  | 'isToezicht'
  | 'isOnderzoekKledingLichaam'
  | 'isOnderzoekWoonruimte'
  | 'isControlerenMiddelen'
  | 'isBeperkenEigenLeven'
  | 'isBeperkenBezoek'
  | 'isOpnemen'
  | 'isTijdelijkVerblijf';
